.PHONY: clean All

All:
	@echo "----------Building project:[ apt32f101a - BuildSet ]----------"
	@cd "D:\Project\MCU\APT_lib\APT32F101\Release Version\APT32F101_Release_V1_20\Source\Application" && make -f  "apt32f101a.mk"
clean:
	@echo "----------Cleaning project:[ apt32f101a - BuildSet ]----------"
	@cd "D:\Project\MCU\APT_lib\APT32F101\Release Version\APT32F101_Release_V1_20\Source\Application" && make -f  "apt32f101a.mk" clean
